name: Actions_Test

on:
  push:
    branches:
      - main
      
jobs:
  FIRST_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "Hello, EveryOne. It's test"
  
  SECOND_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: echo "Hell too, it's second test"
        
  build:
    runs-on: ubuntu-latest
    name: stage_second
    needs: [SECOND_JOB]
    steps:
      - name: test3
        run: mkdir folder && cd folder && touch file.json && echo "test_script" > file.json
    
